sudo: false
language: rust
rust:
- 1.33.0  # Oldest compatible version
- stable
- beta
- nightly
os:
- linux
- osx
matrix:
  include:
  - env: RUSTFMT
    rust: 1.33.0  # `stable`: Locking down for consistent behavior
    install:
      - rustup component add rustfmt
    script:
      - cargo fmt -- --check
  - env: RUSTFLAGS="-D warnings"
    rust: 1.33.0  # `stable`: Locking down for consistent behavior
    install:
    script:
    - cargo check --tests --all-features
  - env: CLIPPY
    rust: 1.33.0  # `stable`: Locking down for consistent behavior
    install:
      - rustup component add clippy
    script:
      - cargo clippy --all-features

install:
- rustc -Vv
- cargo -V
- export PATH=$HOME/.cargo/bin:$PATH

script:
- cargo check --verbose
- cargo check --verbose --no-default-features
- cargo check --verbose --all-features
- rm -rf target/debug/deps/*clap-cargo*  # Avoid docmatic problems
- cargo test  --verbose --all-features

branches:
  only:
  # Release tags
  - /^v\d+\.\d+\.\d+.*$/
  - master

cache:
  directories:
    - /home/travis/.cargo
# But don't cache the cargo registry
before_cache:
- rm -rf $HOME/.cargo/registry
# Travis can't cache files that are not readable by "others"
- chmod -R a+r $HOME/.cargo

notifications:
  email:
    on_success: never
