stages:
 - template: azure/stages.yml@templates
   parameters:
     minrust: 1.33.0
     codecov_token: $(CODECOV_TOKEN_SECRET)
     test_features: "cargo_metadata"

resources:
  repositories:
    - repository: templates
      type: github
      name: crate-ci/azure-pipelines
      endpoint: crate-ci
