[package]
name = "clap-cargo"
version = "0.1.2"
description = "Re-usable CLI flags for `cargo` plugins"
keywords = ["cargo"]
categories = ["development-tools::cargo-plugins"]
repository = "https://github.com/cobalt-org/clap-cargo"
documentation = "https://docs.rs/clap-cargo"
readme = "README.md"
authors = ["Ed Page <eopage@gmail.com>"]
edition = "2018"
license = "MIT"

[badges]
travis-ci = { repository = "crate-ci/clap-cargo" }
appveyor  = { repository = "epage/clap-cargo" }

[features]

[dependencies]
structopt = "0.2.10"
cargo_metadata = { version = "0.7", optional = true }

[package.metadata.docs.rs]
features = [ "cargo_metadata" ]
