pre-release-commit-message = "chore: Release"
tag-message = "{{tag_name}}"
tag-name = "{{prefix}}v{{version}}"
enable-all-features = true
consolidate-commits = true
consolidate-pushes = true
allow-branch = ["master"]
